name: Build-And-Push-Multiarch

on:
  push:
    branches: [main]
    tags: ["v*.*.*"]

# ────────── ZMIENNE DO PODMIANY ──────────
env:
  GHCR_IMAGE: ghcr.io/szymonzychyoyo/lab8docker2zadanie # <-- ZMIEN
  DOCKERHUB_USER: szymonz123 # <-- ZMIEN
  CACHE_IMAGE: szymonz123/repozytorium2zadanie:cache # <-- ZMIEN

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write # konieczne do pushu w GHCR

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # QEMU + Buildx
      - uses: docker/setup-qemu-action@v3
        name: Set up QEMU

      - uses: docker/setup-buildx-action@v3
        name: Set up Buildx
        with:
          install: true

      # ────────── LOGOWANIA ──────────
      # GHCR – wbudowany GITHUB_TOKEN (nie musisz nic dodawać)
      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Docker Hub – jedyny sekret DH_TOKEN
      - name: Login to DockerHub (cache)
        uses: docker/login-action@v3
        with:
          username: ${{ env.DOCKERHUB_USER }} # jawnie, to nie tajemnica
          password: ${{ secrets.DH_TOKEN }} # JEDYNY sekret jaki masz

      # ────────── BUILD -> SCAN (tylko amd64) ──────────
      - name: Build amd64 for scan
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64
          #load: true
          push: false
          tags: ${{ env.GHCR_IMAGE }}:scan
          cache-from: type=registry,ref=${{ env.CACHE_IMAGE }}
          cache-to: type=registry,ref=${{ env.CACHE_IMAGE }},mode=max

      # ────────── TRIVY ──────────
      - name: Scan image with Trivy
        uses: aquasecurity/trivy-action@0.30.0
        with:
          image-ref: ${{ env.GHCR_IMAGE }}:scan
          exit-code: "0"
          severity: "CRITICAL,HIGH"

      # ────────── BUILD MULTI-ARCH + PUSH ──────────
      - name: Build & Push multi-arch
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ${{ env.GHCR_IMAGE }}:latest
            ${{ env.GHCR_IMAGE }}:${{ github.sha }}
          cache-from: type=registry,ref=${{ env.CACHE_IMAGE }}
          cache-to: type=registry,ref=${{ env.CACHE_IMAGE }},mode=max
          provenance: false
